---
keys:
  - &thomas age1s8sasdxlc8yzw47pqgh0swwhkpergq943jzmc49n6vx7ct7nfucsaqq68t
  - &xenoi age17kj9me6rluhq3xwfd0c7rs7wlzez7qgp34878ap80sxvk59fg3qqz8dlup
  - &poseidon age1pfyuh53qv5jg4ege7y0nypg7ddx5mdfnsl40pnmsg0xxuymcfu8qmavma9

creation_rules:
  - path_regex: secrets/secrets.json$|secrets/ssh.yaml$
    key_groups:
      - age:
        - *thomas
        - *xenoi
        - *poseidon

  - path_regex: secrets/irssi.yml$
    key_groups:
      - age:
          - *thomas
          - *xenoi
